name: Bug
description: Report a bug
labels: [bug]
body:
  - type: textarea
    id: who
    attributes:
      label: Who
      description: Who is affected.
    validations:
      required: true
  - type: textarea
    id: what
    attributes:
      label: What
      description: What went wrong.
    validations:
      required: true
  - type: textarea
    id: when
    attributes:
      label: When
      description: When it happens.
    validations:
      required: true
  - type: textarea
    id: where
    attributes:
      label: Where
      description: Version and environment.
    validations:
      required: true
  - type: textarea
    id: why
    attributes:
      label: Why
      description: Expected versus actual.
    validations:
      required: true
  - type: textarea
    id: how
    attributes:
      label: How
      description: How to reproduce.
    validations:
      required: true
